(RFC) Use an 'urgency' flag to decide whether to pop-up the goals buffer
FStarLang/fstar-mode.el pull request #122
Opened 2020-09-25 14:47 UTC by mtzguido

Hi Clément,

with @R1kM and others we were finding the fact that the goals buffers always opens up on a tactics error a bit annoying (especially when many buffers are open). So I came up with this patch to decide whether to display it or not. The idea is that F* provides and "urgency" level for each proofstate (currently just 0 or 1), and emacs will only pop-up the buffer when it is 1 (but will always log the error in the buffer). The urgency is 1 by default to not affect the old behavior.

Does this look sensible to you? I would imagine there's probably better ways to do it :-)

(F* `master` doesn't pass the urgency field yet, `guido_tactics` does).

2020-10-01 02:08 UTC, cpitclaudel requested changes
Looks reasonable to me, and it's not much code at all.  I left stylistic comments.

2020-10-01 02:08 UTC, cpitclaudel commented on fstar-mode.el
> +is true."
Avoid breaking the docstring's first line.  Hre I think the function does too much.  I would move the `(let ((window …)))` to a separate function and call it from `body` in the caller of this function

2020-10-01 02:08 UTC, cpitclaudel commented on fstar-mode.el
> +     :urgency (if (not .urgency) 1 .urgency)
`(or .urgency 1)` I think

2020-10-01 02:13 UTC, mtzguido commented
Thanks Clément, much appreciated! I'll update this soon.

2020-10-12 00:30 UTC, mtzguido commented
Just updated the PR according to your comments, let me know if I messed something up :). Also used if-let as you mentioned in the other (already merged) PR. Thanks a lot!

2020-10-12 21:29 UTC, cpitclaudel commented on fstar-mode.el
> +          (if-let ((num (fstar-issue-number issue)))
I typically use `-if-let*` (provided by the `dash` library), as `if-let` is only available in newer Emacsen

2020-10-12 21:30 UTC, cpitclaudel commented on fstar-mode.el
> +
I'd remove this

2020-10-12 21:30 UTC, cpitclaudel commented on fstar-mode.el
> +      )))
That's not a very common line wrapping style in elisp

2020-10-12 21:30 UTC, cpitclaudel approved these changes
LGTM, feel free to rebase and merge :)  I left small comments if you want to clean up further before rebasing.

2020-10-12 21:50 UTC, mtzguido commented on fstar-mode.el
> +
oops :)

2020-10-12 22:01 UTC, mtzguido commented
Thanks Clément! I cleaned it up a bit and rebased.

2020-10-12 22:01 UTC, merged